//go:build !windows

package network

import (
	"fmt"
	"net"
	"os"
	"strings"
)

type unixDNS struct {
	origResolvConf []byte
}

func newDNSManager() DNSManager {
	return &unixDNS{}
}

func (d *unixDNS) Set(_ string, servers []string) error {
	if len(servers) == 0 {
		return nil
	}

	// Backup current resolv.conf
	data, err := os.ReadFile("/etc/resolv.conf")
	if err == nil {
		d.origResolvConf = data
	}

	// Validate all DNS server addresses
	for _, server := range servers {
		if net.ParseIP(server) == nil {
			return fmt.Errorf("invalid DNS server address: %q", server)
		}
	}

	// Write new resolv.conf
	var sb strings.Builder
	sb.WriteString("# Generated by VoidVPN\n")
	for _, server := range servers {
		sb.WriteString(fmt.Sprintf("nameserver %s\n", server))
	}

	return os.WriteFile("/etc/resolv.conf", []byte(sb.String()), 0644)
}

func (d *unixDNS) Restore() error {
	if d.origResolvConf == nil {
		return nil
	}
	return os.WriteFile("/etc/resolv.conf", d.origResolvConf, 0644)
}
